//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

public class ConcertMaterialDaO : DaO
{

	internal bool addZenesz(int koncertanyag_id, int users_id, int szolam_id, int koncert_id)
	{
        try
        {
            // Query string 
            string strSQL = "INSERT INTO KONCERT_ZENESZ (koncert_id, users_id, szolam_id, koncertanyag_id) " +
                "VALUES (@_koncert_id, @_users_id, @_szolam_id, @_koncertanyag_id); ";

            // Add query text
            MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@_koncert_id", koncert_id);
            cmd.Parameters.AddWithValue("@_users_id", users_id);
            cmd.Parameters.AddWithValue("@_szolam_id", szolam_id);
            cmd.Parameters.AddWithValue("@_koncertanyag_id", koncertanyag_id);

            // Execute query
            if (cmd.ExecuteNonQuery() != 1)
            {
                return false;
            }

        }
        catch (MySqlException ex)
        {
            Console.WriteLine("MySQL error. Number: " + ex.Number);
            return false;
        }

        return true;
	}


    internal int create(int koncertanyag_id, int koncert_id, int sorszam, int tetel_id, List<KeyValuePair<int, int>> zeneszek)
	{

        MySqlDataReader rdr = null;
        int materialid = -1;

        try
        {
            // koncertanyag tabla adatainak irasa
            // Query string 
            string strSQL = "INSERT INTO KONCERTANYAG (koncert_id, sorszam, tetel_id) "+ 
                "VALUES (@_koncert_id, @_sorszam, @_tetel_id); ";

            // Add query text
            MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@_koncert_id", koncert_id);
            cmd.Parameters.AddWithValue("@_sorszam", sorszam);
            cmd.Parameters.AddWithValue("@_tetel_id", tetel_id);
            // Execute query
            if (cmd.ExecuteNonQuery() != 1)
            {
                return materialid;
            }


            // adatbazisba felvett koncertanyag ID-janak lekerdezese

            string stm = "SELECT koncertanyag_id FROM KONCERTANYAG where koncert_id=@_koncert_id AND sorszam=@_sorszam AND tetel_id=@_tetel_id;";

            cmd = new MySqlCommand(stm, this.Conn);

            cmd.Prepare();
            cmd.Parameters.AddWithValue("@_koncert_id", koncert_id);
            cmd.Parameters.AddWithValue("@_sorszam", sorszam);
            cmd.Parameters.AddWithValue("@_tetel_id", tetel_id);

            // Execute query
            rdr = cmd.ExecuteReader();

            while (rdr.Read())
            {
                materialid = rdr.GetInt32(0);
            }



            // koncert_zenesz tabla adatainak irasa
            // Query string 
            strSQL = "INSERT INTO KONCERT_ZENESZ (koncert_id, users_id, szolam_id, koncertanyag_id) " +
                "VALUES (@_koncert_id, @_users_id, @_szolam_id, @_koncertanyag_id); ";

            // Add query text
            cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            for (int i = 0; i < zeneszek.Count; i++)
            {
                // Add parameter
                cmd.Parameters.AddWithValue("@_koncert_id", koncert_id);
                cmd.Parameters.AddWithValue("@_users_id", zeneszek[i].Key);
                cmd.Parameters.AddWithValue("@_szolam_id", zeneszek[i].Value);
                cmd.Parameters.AddWithValue("@_koncertanyag_id", materialid);
                // Execute query
                cmd.ExecuteNonQuery();
            }
           
        }
        catch (MySqlException ex)
        {
            Console.WriteLine("MySQL error. Number: " + ex.Number);
            return -1;
        }

        finally
        {
            if (rdr != null)
            {
                rdr.Close();
            }

        }

        return materialid;

	}


    internal bool deleteZenesz(int koncertanyag_id, int users_id, int szolam_id)
	{
       
        try
        {
            // Query string 
            string strSQL = "DELETE FROM KONCERT_ZENESZ WHERE koncertanyag_id=@_koncertanyag_id AND users_id=@_users_id AND szolam_id=@_szolam_id";

            // Add query text
            MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@_koncertanyag_id", koncertanyag_id);
            cmd.Parameters.AddWithValue("@_users_id", users_id);
            cmd.Parameters.AddWithValue("@_szolam_id", szolam_id);

            // Execute query
            if (cmd.ExecuteNonQuery() != 1)
            {
                return false;
            }

            return true;
        }
        catch (MySqlException ex)
        {
            Console.WriteLine("MySQL error. Number: " + ex.Number);
        }

        return false;
	}


    internal List<KeyValuePair<int, int>> getZeneszek(int koncertanyag_id)
	{
        MySqlDataReader rdr = null;

        var result = new List<KeyValuePair<int, int>>();

        try
        {

            // user adatok lekerdezese
            string stm = "SELECT users_id, szolam_id FROM KONCERT_ZENESZ WHERE koncertanyag_id=@_koncertanyag_id";

            MySqlCommand cmd = new MySqlCommand(stm, this.Conn);

            cmd.Prepare();
            cmd.Parameters.AddWithValue("@_koncertanyag_id", koncertanyag_id);

            rdr = cmd.ExecuteReader();


            while (rdr.Read())
            {
                result.Add(new KeyValuePair<int, int>(rdr.GetInt32(0), rdr.GetInt32(1)));
            }


        }
        catch (MySqlException ex)
        {
            Console.WriteLine("Error: {0}", ex.ToString());

        }
        finally
        {
            if (rdr != null)
            {
                rdr.Close();
            }

        }

        // Return with the result string
        return result;

	}

    internal bool modify(int koncertanyag_id, int koncert_id, int sorszam, int tetel_id, List<KeyValuePair<int, int>> zeneszek)
	{
        try
        {

            // koncertanyag adatok frissitese az adatbazisban

            string strSQL = "UPDATE KONCERTANYAG SET koncert_id=@_koncert_id, sorszam=@_sorszam, tetel_id=@_tetel_id " +
                "WHERE koncertanyag_id=@_koncertanyag_id";

            // Add query text
            MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@_koncert_id", koncert_id);
            cmd.Parameters.AddWithValue("@_sorszam", sorszam);
            cmd.Parameters.AddWithValue("@_tetel_id", tetel_id);
            cmd.Parameters.AddWithValue("@_koncertanyag_id", koncertanyag_id);

            // Execute query
            if (cmd.ExecuteNonQuery() != 1)
            {
                return false;
            }



            // koncert zeneszek torlese az adatbazisbol, hogy aztan a frissitett listat be lehessen irni

            strSQL = "DELETE FROM KONCERT_ZENESZ WHERE koncertanyag_id=@_koncertanyag_id";

            // Add query text
            cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@_koncertanyag_id", koncertanyag_id);

            // Execute query
            if (cmd.ExecuteNonQuery() != 1)
            {
                return false;
            }


            // koncert_zenesz tabla adatainak irasa
            // Query string 
            strSQL = "INSERT INTO KONCERT_ZENESZ (koncert_id, users_id, szolam_id, koncertanyag_id) " +
                "VALUES (@_koncert_id, @_users_id, @_szolam_id, @_koncertanyag_id); ";

            // Add query text
            cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            for (int i = 0; i < zeneszek.Count; i++)
            {
                // Add parameter
                cmd.Parameters.AddWithValue("@_koncert_id", koncert_id);
                cmd.Parameters.AddWithValue("@_users_id", zeneszek[i].Key);
                cmd.Parameters.AddWithValue("@_szolam_id", zeneszek[i].Value);
                cmd.Parameters.AddWithValue("@_koncertanyag_id", koncertanyag_id);
                // Execute query
                cmd.ExecuteNonQuery();
            }

            return true;
        }
        catch (MySqlException ex)
        {
            Console.WriteLine("Error: {0}", ex.ToString());

        }

        return false;
	}

    internal int[] read(int koncertanyag_id, ref List<KeyValuePair<int, int>> zeneszek)
	{


        MySqlDataReader rdr = null;

        var result = new int[4];

        try
        {

            // user adatok lekerdezese

            string stm = "SELECT koncertanyag_id, koncert_id, sorszam, tetel_id " +
             "FROM KONCERTANYAG WHERE koncertanyag_id=@_koncertanyag_id";

            MySqlCommand cmd = new MySqlCommand(stm, this.Conn);

            cmd.Prepare();
            cmd.Parameters.AddWithValue("@_koncertanyag_id", koncertanyag_id);

            rdr = cmd.ExecuteReader();



            while (rdr.Read())
            {
                for (int i = 0; i < 4; i++)
                {
                    result[i] = rdr.GetInt32(i);
                }
            }



            // szolamzeneszek listajanak lekerdezese

            var szolamzeneszek = new List<KeyValuePair<int, int>();

            stm = "SELECT users_id, szolam_idFROM KONCERT_ZENESZ "
                + "WHERE koncertanyag_id=@_koncertanyag_id;";

            cmd = new MySqlCommand(stm, this.Conn);

            cmd.Prepare();
            cmd.Parameters.AddWithValue("@_koncertanyag_id", koncertanyag_id);

            rdr = cmd.ExecuteReader();

            while (rdr.Read())
            {
                int user = rdr.GetInt32(0);
                int szolam = rdr.GetInt32(1);

                szolamzeneszek.Add(new KeyValuePair<int, int>(user, szolam));
            }

            // szolamzeneszek listajanak atadasa parameterben
            zeneszek = szolamzeneszek;


        }
        catch (MySqlException ex)
        {
            Console.WriteLine("Error: {0}", ex.ToString());

        }
        finally
        {
            if (rdr != null)
            {
                rdr.Close();
            }

        }

        // Return with the result string
        return result;
	}

}

