//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net.Mail;
using System.Net;

public class Email
{
    private string email;

    private string name;

    private string password;

    private string server;

    private int port;

    private bool ssl;

    public Email() 
    {
        email="peszmenedzser@gmail.com";
        name = "PESZ Menedzser";
        password = "peszmenedzser123";
        server = "smtp.gmail.com";
        port = 587;
        ssl = true;
    }

	public bool send(KeyValuePair<string, string> to, string subject, string body)
	{


        var fromAddress = new MailAddress(email, name);
        //var toAddress = new MailAddress("gorogbence@gmail.com", "Görög G. Bence");
        var toAddress = new MailAddress(to.Key, to.Value);

        var smtp = new SmtpClient
        {
            Host = server,
            Port = port,
            EnableSsl = ssl,
            DeliveryMethod = SmtpDeliveryMethod.Network,
            UseDefaultCredentials = false,
            Credentials = new NetworkCredential(fromAddress.Address, password)
        };
        using (var message = new MailMessage(fromAddress, toAddress)
        {
            Subject = subject,
            Body = body
        })
        {
            smtp.Send(message);
        }

        return true;

	}

}

