//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Guest
{
	private string email
	{
		get;
		set;
	}

	private string password
	{
		get;
		set;
	}

	private void signUp()
	{
		throw new System.NotImplementedException();
	}

	private void signIn()
	{
		throw new System.NotImplementedException();
	}

}

