//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

public class LogDaO : DaO
{
    public virtual bool adddata(int users_id, string muvelet, string idopont, string uzenet)
    {

        try
        {
            // Query string 
            string strSQL = "INSERT INTO LOG (users_id, muvelet, idopont, uzenet " +
            " VALUES (@_users_id, @_muvelet, @_idopont, @_uzenet); ";

            // Add query text
            MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@_users_id", users_id);
            cmd.Parameters.AddWithValue("@_muvelet", muvelet);
            cmd.Parameters.AddWithValue("@_idopont", idopont);
            cmd.Parameters.AddWithValue("@_uzenet", uzenet);

            // Execute query
            if (cmd.ExecuteNonQuery() != 1)
            {
                return false;
            }

            return true;
        }
        catch (MySqlException ex)
        {
            Console.WriteLine("MySQL error. Number: " + ex.Number);
            return false;
        }

    }

}
