//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MovementDaO : DaO
{
	private bool writeMovementdata(int darab_id, string tetel_cim, int tetel_id, int tetel_szama)
	{
		throw new System.NotImplementedException();
	}

	private bool deletePart(int szolam_id, int tetel_id)
	{
		throw new System.NotImplementedException();
	}

	private List<Integer[]> getAllPartdata(int tetel_id)
	{
		throw new System.NotImplementedException();
	}

	private Integer[] getPart(int szolam_id)
	{
		throw new System.NotImplementedException();
	}

	private int getCountPart(int tetel_id)
	{
		throw new System.NotImplementedException();
	}

	private bool modifyMovementdata(int darab_id, string tetel_cim, int tetel_id, int tetel_szama)
	{
		throw new System.NotImplementedException();
	}

	private Integer[] readMovementdata(int tetel_id)
	{
		throw new System.NotImplementedException();
	}

}

