//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Movement
{
	private int tetel_id
	{
		get;
		set;
	}

	private int darab_id
	{
		get;
		set;
	}

	private string tetel_cim
	{
		get;
		set;
	}

	private int tetel_szama
	{
		get;
		set;
	}

	public virtual MovementDaO MovementDaO
	{
		get;
		set;
	}

	public virtual bool createMovement()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool modifyMovement()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool readMovement(int tetel_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool addPart(Part part)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool deletePart(int szolam_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<Part> getAllParts()
	{
		throw new System.NotImplementedException();
	}

	public virtual Part getPart(int szolam_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual int getCountPart(int tetel_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual Piece getPiece()
	{
		throw new System.NotImplementedException();
	}

}

