//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Part
{
    private int szolam_id;

    public int Szolam_id
    {
        get { return szolam_id; }
        set { szolam_id = value; }
    }


    private int tetel_id;

    public int Tetel_id
    {
        get { return tetel_id; }
        set { tetel_id = value; }
    }


    private int hangszer_id;
	
    public int Hangszer_id
    {
      get { return hangszer_id; }
      set { hangszer_id = value; }
    }

    private int szolamlista_id;

    public int Szolamlista_id
    {
        get { return szolamlista_id; }
        set { szolamlista_id = value; }
    }


    private int szolamkotta_id;

    public int Szolamkotta_id
    {
        get { return szolamkotta_id; }
        set { szolamkotta_id = value; }
    }


    protected virtual PartDaO partDaO;


    public Part()
    {
        partDaO = new PartDaO();
    }
    public Part(int hangszer_id, int szolamkotta_id, int szolamlista_id, int szolam_id, int tetel_id)
    {
        partDaO = new PartDaO();
        this.hangszer_id = hangszer_id;
        this.szolamkotta_id = szolamkotta_id;
        this.szolamlista_id = szolamlista_id;
        this.szolam_id = szolam_id;
        this.tetel_id = tetel_id;
    }


	public virtual bool createPart()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool modifyPart()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool readPart(int szolam_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool addPartpaper(string szolamkotta_link)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool modifyPartpaper(string szolamkotta_link)
	{
		throw new System.NotImplementedException();
	}

	public virtual string getPartpaperlink()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getPartname()
	{
		throw new System.NotImplementedException();
	}

	public virtual List<KeyValuePair<Integer, String>> getPartList()
	{
		throw new System.NotImplementedException();
	}

	public virtual Movement getMovement()
	{
		throw new System.NotImplementedException();
	}

}

