//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Part
{
    private int szolam_id;

    public int Szolam_id
    {
        get { return szolam_id; }
        set { szolam_id = value; }
    }


    private int tetel_id;

    public int Tetel_id
    {
        get { return tetel_id; }
        set { tetel_id = value; }
    }


    private int hangszer_id;
	
    public int Hangszer_id
    {
      get { return hangszer_id; }
      set { hangszer_id = value; }
    }

    private int szolamlista_id;

    public int Szolamlista_id
    {
        get { return szolamlista_id; }
        set { szolamlista_id = value; }
    }


    private int szolamkotta_id;

    public int Szolamkotta_id
    {
        get { return szolamkotta_id; }
        set { szolamkotta_id = value; }
    }


    protected PartDaO partDaO;


    public Part()
    {
        partDaO = new PartDaO();
    }


    public Part(int szolam_id, int tetel_id, int hangszer_id, int szolamlista_id, int szolamkotta_id)
    {
        partDaO = new PartDaO();
        this.hangszer_id = hangszer_id;
        this.szolamkotta_id = szolamkotta_id;
        this.szolamlista_id = szolamlista_id;
        this.szolam_id = szolam_id;
        this.tetel_id = tetel_id;
    }


	public bool createPart()
	{
        szolam_id = partDaO.writePartdata(hangszer_id, szolamkotta_id, szolamlista_id, tetel_id);
        if (szolam_id > -1)
        {
            return true;
        }
        else
        {
            return false;
        }
	}


	public bool modifyPart()
	{
        return partDaO.modifyPartdata(hangszer_id, szolamkotta_id, szolamlista_id, szolam_id, tetel_id);
	}


	public bool readPart(int szolam_id)
	{
        var data = new int[5];
        data = partDaO.readPartdata(szolam_id);

        szolam_id =data[0];
        tetel_id = data[1];
        hangszer_id = data[2];
        szolamlista_id = data[3];
        szolamkotta_id = data[4];

        return true;
	}


	public bool addPartpaper(string szolamkotta_link)
	{
        szolamkotta_id = partDaO.writePartpaper(szolamkotta_link);
        if (szolamlista_id > -1)
        {
            return true;
        }
        else
        {
            return false;
        }
	}


	public bool modifyPartpaper(string szolamkotta_link)
	{
        return partDaO.modifyPartpaper(szolamkotta_link, this.szolamlista_id);
	}


	public string getPartpaperlink()
	{
        return partDaO.getPartPaper(szolamkotta_id);
	}


	public string getPartname()
	{
        return partDaO.getPartname(szolamlista_id);
	}


    public List<KeyValuePair<int, KeyValuePair<string, int>>> getPartList()
	{
        return partDaO.getPartListData();
	}


	public Movement getMovement()
	{
        var movement = new Movement();
        movement.readMovement(this.tetel_id);
        return movement;
	}

}

