//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

public class PartDaO : DaO
{
	internal int writePartdata(int hangszer_id, int szolamkotta_id, int szolamlista_id, int tetel_id)
	{

        MySqlDataReader rdr = null;
        int partid = 0;

        try
        {
            // szolam adatainak irasa
            // Query string 
            string strSQL = "INSERT INTO SZOLAM (hangszer_id, szolamkotta_id, szolamlista_id, tetel_id) VALUES (@_hangszer_id, " +
                "@_szolamkotta_id, @_szolamlista_id, @_tetel_id); ";

            // Add query text
            MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@_hangszer_id", hangszer_id);
            cmd.Parameters.AddWithValue("@_szolamkotta_id", szolamkotta_id);
            cmd.Parameters.AddWithValue("@_szolamlista_id", szolamlista_id);
            cmd.Parameters.AddWithValue("@_tetel_id", tetel_id);
            // Execute query
            if (cmd.ExecuteNonQuery() != 1)
            {
                return partid;
            }
            

            // adatbazisba felvett Part ID-janak lekerdezese

            string stm = "SELECT szolam_id FROM SZOLAM where hangszer_id=@_hangszer_id AND szolamkotta_id=@_szolamkotta_id " +
                "AND szolamlista_id=@_szolamlista_id AND tetel_id=@_tetel_id";

            cmd = new MySqlCommand(stm, this.Conn);

            cmd.Prepare();
            cmd.Parameters.AddWithValue("@_hangszer_id", hangszer_id);
            cmd.Parameters.AddWithValue("@_szolamkotta_id", szolamkotta_id);
            cmd.Parameters.AddWithValue("@_szolamlista_id", szolamlista_id);
            cmd.Parameters.AddWithValue("@_tetel_id", tetel_id);

            rdr = cmd.ExecuteReader();

            while (rdr.Read())
            {
                partid = rdr.GetInt32(0);
            }


            return partid;
        }
        catch (MySqlException ex)
        {
            Console.WriteLine("MySQL error. Number: " + ex.Number);
            return 0;
        }

        finally
        {
            if (rdr != null)
            {
                rdr.Close();
            }

        }

	}


	internal bool modifyPartdata(int hangszer_id, int szolamkotta_id, int szolamlista_id, int szolam_id, int tetel_id)
	{
		
        try
        {
           
            // user adatok frissitese az adatbazisban
 
            string strSQL = "UPDATE SZOLAM SET hangszer_id=@_hangszer_id, szolamkotta_id=@_szolamkotta_id, " +
                    "szolamlista_id=@_szolamlista_id, tetel_id=@_tetel_id WHERE szolam_id=@_szolam_id";

            // Add query text
            MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@_szolam_id", szolam_id);
            cmd.Parameters.AddWithValue("@_hangszer_id", hangszer_id);
            cmd.Parameters.AddWithValue("@_szolamkotta_id", szolamkotta_id);
            cmd.Parameters.AddWithValue("@_szolamlista_id", szolamlista_id);
            cmd.Parameters.AddWithValue("@_tetel_id", tetel_id);

            // Execute query
            if (cmd.ExecuteNonQuery() == 1)
            {
                return true;
            }

        }
        catch (MySqlException ex)
        {
            Console.WriteLine("Error: {0}", ex.ToString());

        }

        return true;

	}

	internal string getPartPaper(int szolamkotta_id)
	{
		throw new System.NotImplementedException();
	}

	internal List<KeyValuePair<int, KeyValuePair<string, int>>> getPartListData()
	{
		throw new System.NotImplementedException();
	}

	internal int writePartpaper(string szolamkotta_link)
	{
		throw new System.NotImplementedException();
	}

	internal string getPartname(string szolamlista_id)
	{
		throw new System.NotImplementedException();
	}

	internal bool modifyPartpaper(string szolamkott_link)
	{
		throw new System.NotImplementedException();
	}

	internal string[] readPartdata(int szolam_id)
	{
		throw new System.NotImplementedException();
	}

}

