//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Piece
{
	private int darab_id
	{
		get;
		set;
	}

	private string darab_szerzo
	{
		get;
		set;
	}

	private string darab_cim
	{
		get;
		set;
	}

	private int tetelszam
	{
		get;
		set;
	}

	public virtual PieceDaO PieceDaO
	{
		get;
		set;
	}

	public virtual List<Movement> getAllMovements()
	{
		throw new System.NotImplementedException();
	}

	public virtual Movement getMovement(int tetel_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool addMovement(Movement movement)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool deleteMovement(int tetel_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool readPiece(int darab_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool createPiece()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool modifyPiece()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getCountMovements()
	{
		throw new System.NotImplementedException();
	}

}

