//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PieceDaO : DaO
{
	private bool writePiecedata(string darab_cim, int darab_id, string darab_szerzo, int tetelszam)
	{
		throw new System.NotImplementedException();
	}

	private bool deleteMovementdata(int tetel_id)
	{
		throw new System.NotImplementedException();
	}

	private List<String[]> getAllMovementsdata(int darab_id)
	{
		throw new System.NotImplementedException();
	}

	private int getCountMovements(int darab_id)
	{
		throw new System.NotImplementedException();
	}

	private String[] getMovementdata(int darab_id)
	{
		throw new System.NotImplementedException();
	}

	private bool modifyPiecedata(string darab_cim, int darab_id, string darab_szerzo, int tetelszam)
	{
		throw new System.NotImplementedException();
	}

	private String[] readPiecedata(int darab_id)
	{
		throw new System.NotImplementedException();
	}

}

