//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Rehearsal
{
    private int proba_id;

    public int Proba_id
    {
        get { return proba_id; }
        set { proba_id = value; }
    }


    private string idopont;

    public string Idopont
    {
        get { return idopont; }
        set { idopont = value; }
    }


    private string helyszin;

    public string Helyszin
    {
        get { return helyszin; }
        set { helyszin = value; }
    }


    private string megjegyzes;

    public string Megjegyzes
    {
        get { return megjegyzes; }
        set { megjegyzes = value; }
    }


    private List<KeyValuePair<int, bool>> resztvett;

    public List<KeyValuePair<int, bool>> Resztvett
    {
        get { return resztvett; }
        set { resztvett = value; }
    }


    private List<KeyValuePair<int, KeyValuePair<bool, string>>> tervezett_reszvetel;

    public List<KeyValuePair<int, KeyValuePair<bool, string>>> Tervezett_reszvetel
    {
        get { return tervezett_reszvetel; }
        set { tervezett_reszvetel = value; }
    }


    private RehearsalDaO rehearsalDaO;


    public Rehearsal()
    {
        rehearsalDaO = new RehearsalDaO();
        tervezett_reszvetel = new List<KeyValuePair<int, KeyValuePair<bool, string>>>();
        resztvett = new List<KeyValuePair<int, bool>>();
    }

    public Rehearsal(string idopont, string helyszin, string megjegyzes, List<KeyValuePair<int, bool>> resztvett, List<KeyValuePair<int, KeyValuePair<bool, string>>> tervezett_reszvetel)
    {
        rehearsalDaO = new RehearsalDaO();
        tervezett_reszvetel = new List<KeyValuePair<int, KeyValuePair<bool, string>>>();
        resztvett = new List<KeyValuePair<int, bool>>();

        this.idopont = idopont;
        this.helyszin = helyszin;
        this.megjegyzes = megjegyzes;
        this.resztvett = resztvett;
        this.tervezett_reszvetel = tervezett_reszvetel;
    }


	public bool create()
	{
        proba_id = rehearsalDaO.writeRehearsalData(helyszin, idopont, megjegyzes, proba_id, resztvett, tervezett_reszvetel);
        if (proba_id > -1)
        {
            return true;
        }
        else
        {
            return false;
        }
	}


	public List<KeyValuePair<int, bool>> getAllReszvetel()
	{
        return rehearsalDaO.getAllReszvetel(proba_id);
	}


	public bool getReszvetel(int users_id)
	{
        return rehearsalDaO.getReszvetel(proba_id, users_id);
	}


	public KeyValuePair<bool, string> getTervezettReszvetel(int users_id)
	{
        return rehearsalDaO.getTervezettReszvetel(proba_id, users_id);
	}


	public List<Part> getUsersParts(int users_id)
	{
		var data = new List<int>();
        var result = new List<Part>();

        data = rehearsalDaO.getUsersParts(users_id);

        for (int i = 0; i < data.Count; i++)
        {
            var part = new Part();
            part.readPart(data[i]);
            result.Add(part);
        }

        return result;
	}

	public bool modify()
	{
        return rehearsalDaO.modifyRehearsalData(helyszin, idopont, megjegyzes, proba_id, resztvett, tervezett_reszvetel);
	}

	public bool modifyReszvetel(int users_id, bool resztvesz, string indoklas)
	{
        return rehearsalDaO.modifyReszvetel(proba_id, users_id, resztvesz, indoklas);
	}

	public bool read(int proba_id)
	{
        var data = new string[4];

        data = rehearsalDaO.readRehearsalData(proba_id, ref resztvett, ref tervezett_reszvetel);

        this.proba_id = Convert.ToInt32(data[0]);
        this.idopont = data[1];
        this.helyszin = data[2];
        this.megjegyzes = data[3];

        return true;
	}

}

