//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

public class UserDaO : DaO
{
	internal bool writeUserdata(string users_nev, string users_email, int jogkor_id, 
        bool aktiv, bool koncertre_jar, string users_password)
	{
        try
        {
            // Query string 
            string strSQL = "INSERT INTO USERS (users_nev, users_email, jogkor_id, aktiv, " +
            "koncertre_jar, users_password) VALUES (@nev, @email, @jogkor, @_aktiv, " +
            "@_koncertre_jar, @password); ";

            // Add query text
            MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

            // Prepare the query
            cmd.Prepare();

            // Add parameter
            cmd.Parameters.AddWithValue("@nev", users_nev.ToString());
            cmd.Parameters.AddWithValue("@email", users_email.ToString());
            cmd.Parameters.AddWithValue("@jogkor", jogkor_id.ToString());
            cmd.Parameters.AddWithValue("@_aktiv", aktiv.ToString());
            cmd.Parameters.AddWithValue("@_koncertre_jar", koncertre_jar.ToString());
            cmd.Parameters.AddWithValue("@password", users_password.ToString());

            // Execute query
            if (cmd.ExecuteNonQuery() == 1)
            {
                return true;
            }
            return false;
        }
        catch (MySqlException ex)
        {
            Console.WriteLine("MySQL error. Number: " + ex.Number);
            return false;
        }
        //return true;
	}


	internal string[] readUserdata(string email)
	{
       
        MySqlDataReader rdr = null;

        var result = new string[7];

        try
        {
            
            string stm = "SELECT users_id, users_nev, users_email, jogkor_id, aktiv, " +
             "koncertre_jar, users_password FROM USERS where users_email=@email";
           
            MySqlCommand cmd = new MySqlCommand(stm, this.Conn);

            cmd.Prepare();
            cmd.Parameters.AddWithValue("@email", email);

            rdr = cmd.ExecuteReader();

            

            while (rdr.Read())
            {
                for (int i = 0; i < 7; i++)
                {
                    result[i] = rdr.GetString(i);
                }
            }

        }
        catch (MySqlException ex)
        {
            Console.WriteLine("Error: {0}", ex.ToString());

        }
        finally
        {
            if (rdr != null)
            {
                rdr.Close();
            }

        }

        // Return with the result string
        return result;
	}

	internal bool modifyUserdata(int users_id, string users_nev, string users_email, int jogkor_id, bool aktiv, bool koncertre_jar, string users_password)
	{
        // Query string 
        string strSQL = "UPDATE USERS SET users_nev=@_nev, " +
        "users_email=@_email, jogkor_id=@_jogkor, aktiv=@_aktiv, " +
        "koncertre_jar=@_koncertre_jar, users_password=@_password WHERE users_id=@_id";

        // Add query text
        MySqlCommand cmd = new MySqlCommand(strSQL, this.Conn);

        // Prepare the query
        cmd.Prepare();

        // Add parameter
        cmd.Parameters.AddWithValue("@_id", users_id);
        cmd.Parameters.AddWithValue("@_nev", users_nev);
        cmd.Parameters.AddWithValue("@_email", users_email);
        cmd.Parameters.AddWithValue("@_jogkor", jogkor_id);
        cmd.Parameters.AddWithValue("@_aktiv", aktiv);
        cmd.Parameters.AddWithValue("@_koncertre_jar", koncertre_jar);
        cmd.Parameters.AddWithValue("@_password", users_password);

        // Execute query
        if (cmd.ExecuteNonQuery() == 1)
        {
            return true;
        }
        return false;
	}

}

