//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
    private int users_id;
    public int Users_id
    {
        get { return users_id; }
        set { users_id = value; }
    }


    private string users_email;
    public string Users_email
    {
        get { return users_email; }
        set { users_email = value; }
    }

    private int jogkor_id;
    public int Jogkor_id
    {
        get { return jogkor_id; }
        set { jogkor_id = value; }
    }

    private bool aktiv;
    public bool Aktiv
    {
        get { return aktiv; }
        set { aktiv = value; }
    }


    private bool koncertre_jar;
    public bool Koncertre_jar
    {
        get { return koncertre_jar; }
        set { koncertre_jar = value; }
    }

    private string users_password;
    public string Users_password
    {
        get { return users_password; }
        set { users_password = value; }
    }


    private string users_nev;
    public string Users_nev
    {
        get { return users_nev; }
        set { users_nev = value; }
    }

	public virtual UserDaO UserDaO
	{
		get;
		set;
	}

    public User()
    {
        users_password = "123";
        users_id = 2;
    }

	public bool profileModify()
	{
        return UserDaO.modifyUserdata(users_id, users_nev, users_email, jogkor_id, aktiv, koncertre_jar, users_password);
	}

	public Message[] getMessages()
	{
		throw new System.NotImplementedException();
	}

	public bool readMessage(Message uzenet)
	{
		throw new System.NotImplementedException();
	}

	public bool createProfile()
	{

        Console.WriteLine("Próba adatok: ");

        Console.WriteLine(users_email);
        Console.WriteLine(users_nev);
        Console.WriteLine(users_password);
        Console.WriteLine(aktiv);
        Console.WriteLine(koncertre_jar);
        Console.WriteLine(jogkor_id);

        

        try
        {
            return UserDaO.writeUserdata(users_nev, users_email, jogkor_id, aktiv, koncertre_jar, users_password);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Exception. Number: "+ ex.ToString());
            return false;
        }
        
	}

    public bool readProfile(string email)
    {
        string []data;
        data = UserDaO.readUserdata(email);

        this.users_id = Int32.Parse(data[0]);
        this.users_nev = data[1];
        this.users_email = data[2];
        this.jogkor_id = Int32.Parse(data[3]);
        this.aktiv = (data[4]=="true"?true:false);
        this.koncertre_jar = (data[5] == "true" ? true : false);
        this.users_password = data[6];

        return true;
    }

}

