//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	private int users_id
	{
		get;
		set;
	}

	private string users_email
	{
		get;
		set;
	}

	private int jogkor_id
	{
		get;
		set;
	}

	private bool aktiv
	{
		get;
		set;
	}

	private bool koncertre_jar
	{
		get;
		set;
	}

	private string users_password
	{
		get;
		set;
	}

	private string users_nev
	{
		get;
		set;
	}

	private void profileModify()
	{
		throw new System.NotImplementedException();
	}

	private void getMessages()
	{
		throw new System.NotImplementedException();
	}

	public virtual void -readMessage(int uzenet_id)
	{
		throw new System.NotImplementedException();
	}

}

